services:
  db:
    image: mariadb:12
    environment:
      MARIADB_USER: books
      MARIADB_PASSWORD: bookspw
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: booksdb
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      # https://github.com/docker-library/healthcheck/blob/master/mysql/Dockerfile.mariadb
      test: ['CMD', 'healthcheck.sh', '--su=mysql', '--connect', '--innodb_initialized']
      timeout: 10s
      retries: 3

  # Web-based UI for Kafka (this time on http://localhost:9001)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9001:8080
    depends_on:
      kafka-0:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'

  kafka-0:
    image: apache/kafka:4.1.1
    volumes:
      - kafka_0_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9093,3@kafka-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      # Enabled JMX for kafka-ui - would need to be secured in a production environment
      JMX_PORT: 9997
    healthcheck:
      test: ['CMD-SHELL', 'unset JMX_PORT && /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1']
      timeout: 10s
      retries: 3

  kafka-1:
    image: apache/kafka:4.1.1
    volumes:
      - kafka_1_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9093,3@kafka-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      # Enabled JMX for kafka-ui - would need to be secured in a production environment
      JMX_PORT: 9997
    healthcheck:
      test: ['CMD-SHELL', 'unset JMX_PORT && /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1']
      timeout: 10s
      retries: 3

  kafka-2:
    image: apache/kafka:4.1.1
    volumes:
      - kafka_2_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:9093,2@kafka-1:9093,3@kafka-2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      # Enabled JMX for kafka-ui - would need to be secured in a production environment
      JMX_PORT: 9997
    healthcheck:
      test: ['CMD-SHELL', 'unset JMX_PORT && /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1']
      timeout: 10s
      retries: 3

  books:
    image: book-microservice:latest
    ports:
      - 8080:8080
    environment:
      DATASOURCES_DEFAULT_URL: jdbc:mariadb://db/booksdb
      DATASOURCES_DEFAULT_USERNAME: books
      DATASOURCES_DEFAULT_PASSWORD: bookspw
      KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
    depends_on:
      db:
        condition: service_healthy
      kafka-0:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:8080/health']
      timeout: 10s
      retries: 3

volumes:
  mariadb_data:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data: